baseURL = 'https://nostr-ux.com/'
languageCode = 'en-us'
title = 'UX Patterns for Nostr Apps'
theme = 'hextra'
enableGitInfo = true

# Mount existing content
[module]
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "patterns"
    target = "content/docs/patterns"

  [[module.mounts]]
    source = "appendices"
    target = "content/docs/research"

  [[module.mounts]]
    source = "static"
    target = "static"

[params]
  description = 'Evidence-informed patterns for building Nostr apps people actually use'
  images = ['/images/og-image.png']
  displayUpdatedDate = true

  [params.social]
    twitter = "shawnyeager"

  # Plausible.io analytics (custom script in layouts/partials/custom/head-end.html)
  [params.analytics.plausible]
    domain = "nostr-ux.com"
    siteId = "pa-oUUlFJE5n1WlHFNU0tUMt"

  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"

    [params.navbar.logo]
      path = "images/logo.svg"
      dark = "images/logo-dark.svg"
      width = 32
      height = 32

  [params.footer]
    displayCopyright = true
    displayPoweredBy = false

[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1

[[menu.main]]
  name = "Search"
  weight = 4
  [menu.main.params]
    type = "search"

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/shawnyeager/nostr-ux-research"
  weight = 6
  [menu.main.params]
    icon = "github"

[markup]
  [markup.highlight]
    lineNos = false

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = true

[outputs]
  home = ['HTML']
  page = ['HTML']
  section = ['HTML', 'RSS']
